database:
  type: Database
  host: localhost
  database: wwo
  username: root
  password: root

facebook:
  type: Facebook
  config:
    appId: 161054327279516
    secret: 8b1446580556993a34880a831ee36856

#profile_pic_storage:
#  type: FileRepository
#  driver: local
#  path: pics
#  base_url: http://localhost/

profile_pic_storage:
  type: FileRepository
  driver: s3
  bucket: whowentout_development_pics
  amazon_public_key: 0N83TDC3E416BETER2R2
  amazon_secret_key: sKpMFrppw9X2KtuvUgJRyZo+O7yvYPluC4ttAwWK

ticket_storage:
  type: FileRepository
  driver: local
  path: tickets
  base_url: http://localhost/

pusher:
  type: Pusher
  auth_key: 805af8a6919abc9fb047
  secret: 66d4d08ba68b3da6a60f
  app_id: 10138
  debug: true
  timeout: 10

network_blocker:
  type: NetworkBlocker
  database: database
  allowed_networks:
    #- 16777270 #gwu
    - 16777219 #stanford
    #- 16777224 #mit