app:
  type: FireApp
  class_loader: class_loader
  
test_database:
  type: database
  host: localhost
  database: fire_test
  username: root
  password: root

router:
  type: Router
  app: app