app:
  type: WhoWentOutApp
  class_loader: class_loader
  database: database

database:
  type: database
  host: localhost
  database: wwo
  username: root
  password: root

test_database:
  type: database
  host: localhost
  database: fire_test
  username: root
  password: root

router:
  type: Router
  app: app