# TODO: deny access to these directories using .htaccess
app:
  type: WhoWentOutApp
  class_loader: class_loader
  database: database
  clock: clock

route_matcher:
  type: RouteMatcher

router:
  type: ActionRouter
  routes:
    "/": ViewHomepage
    "day": ViewDay
    "day/(:num)": ViewDay/$1
    "login": Login
    "logout": Logout
    "login/complete": LoginComplete
    "login/as/(:num)": LoginAs/$1
    "profile/(:num)": ViewProfile/$1
    "profile/picture/edit": ViewEditProfilePictureDialog
    "profile/picture/facebook": SetProfilePictureToFacebook
    "profile/picture/upload": UploadProfilePicture
    "profile/picture/crop": CropProfilePicture
    "events/(:num)/invite": ViewInviteDialog/$1
    "events/(:num)/invite/submit": SendInvites
    "events/(:num)/deal": ViewDealDialog/$1
    "deal/confirm": ConfirmDeal
    "checkin": Checkin
    "admin": AdminView
    "admin/places": AdminViewPlaces
    "admin/places/create": AdminCreatePlace
    "admin/places/(:num)/destroy": AdminDestroyPlace/$1
    "admin/events": AdminViewEvents
    "admin/events/create": AdminCreateEvent
    "admin/events/(:num)/destroy": AdminDestroyEvent/$1
    "admin/packages": ViewPackages
    "admin/packages/(:alnum)/install": InstallPackage/$1
    "admin/packages/(:alnum)/update": UpdatePackage/$1

asset:
  type: Asset
  index: index

facebook_profile_source:
  type: FacebookProfileSource
  facebook: facebook

facebook_networks_updater:
  type: FacebookNetworksUpdater
  database: database
  profile_source: facebook_profile_source

auth:
  type: FacebookAuth
  facebook: facebook
  database: database
  facebook_permissions:
    - user_birthday
    - user_education_history
    - user_hometown
    - user_events
    - email
    - offline_access
    - publish_stream
    - user_location
    - friends_events
    - friends_education_history

profile_pic_repository:
  type: ImageRepository
  file_repository: profile_pic_storage

ticket_repository:
  type: ImageRepository
  file_repository: ticket_storage

profile_picture_factory:
  type: ProfilePictureFactory
  database: database
  image_repository: profile_pic_repository

timezone:
  type: DateTimeZone
  timezone: UTC

clock:
  type: Clock
  timezone: timezone

session_handler:
  type: DatabaseSessionHandler
  database: database
  clock: clock

package_installer:
  type: PackageInstaller
  database: database
  class_loader: class_loader

test_package_installer:
  type: PackageInstaller
  database: test_database
  class_loader: class_loader

checkin_engine:
  type: CheckinEngine
  database: database
  clock: clock

invite_engine:
  type: InviteEngine
  database: database
  clock: clock

test_invite_engine:
  type: InviteEngine
  database: test_database
  clock: clock

job_queue:
  type: JobQueue
  database: database
  pusher: pusher

facebook_friend_source:
  type: FacebookFriendSource
  facebook: facebook

facebook_friends_updater:
  type: FacebookFriendsUpdater
  database: database
  friend_source: facebook_friend_source

mutual_friends_calculator:
  type: MutualFriendsCalculator
  database: database

entourage_calculator:
  type: EntourageCalculator
  database: database
