# TODO: deny access to these directories using .htaccess

event_dispatcher:
  type: EventDispatcher
  class_loader: class_loader

app:
  type: WhoWentOutApp
  class_loader: class_loader
  database: database
  clock: clock
  event_dispatcher: event_dispatcher

route_matcher:
  type: RouteMatcher

router:
  type: ActionRouter
  app: app
  routes:
    "test": TestAction
    "/": ViewHomepage
    "day": ViewDay
    "networks_required": ViewNetworksRequiredDialog
    "day/(:num)": ViewDay/$1
    "login": Login
    "logout": Logout
    "login/complete": LoginComplete
    "login/as/(:num)": LoginAs/$1
    "profile/(:num)": ViewProfile/$1
    "profile/picture/edit": ViewEditProfilePictureDialog
    "profile/picture/facebook": SetProfilePictureToFacebook
    "profile/picture/upload": UploadProfilePicture
    "profile/picture/crop": CropProfilePicture
    "events/(:num)/invite": ViewInviteDialog/$1
    "events/(:num)/invite/submit": SendInvites
    "events/(:num)/deal": ViewDealDialog/$1
    "deal/confirm": ConfirmDeal
    "checkin": Checkin
    "checkin/explanation/(:num)": ViewCheckinExplanation/$1
    "checkin/explanation/confirm": ConfirmCheckinExplanation
    "admin": AdminView
    "terms": ShowPage/terms
    "mission": ShowPage/mission_statement
    "admin/deals/(:num)/(:num)/(:num)": AdminViewDeals/$1/$2/$3
    "admin/deals": AdminViewDeals
    "admin/places": AdminViewPlaces
    "admin/places/create": AdminCreatePlace
    "admin/places/(:num)/destroy": AdminDestroyPlace/$1
    "admin/events": AdminViewEvents
    "admin/events/create": AdminCreateEvent
    "admin/events/(:num)/edit": AdminEditEvent/$1
    "admin/events/update": AdminUpdateEvent
    "admin/events/(:num)/destroy": AdminDestroyEvent/$1
    "admin/packages": ViewPackages
    "admin/packages/(:alnum)/install": InstallPackage/$1
    "admin/packages/(:alnum)/update": UpdatePackage/$1
    "admin/emails": AdminViewUnsentEmails
    "admin/emails/update": AdminUpdateEmail
    "admin/emails/run_job": AdminRunEmailJob
    "admin/users/destroy/(:num)": AdminDestroyUser/$1
    "jobs/run/(:alnum)": RunJob/$1
    "jobs/client": ViewJobsClient
    "entourage": ViewEntourage
    "entourage/accept": AcceptEntourageRequest
    "entourage/invite": ViewEntourageRequestDialog
    "entourage/invite/submit": SendEntourageRequests
    "leaderboard/(:num)/(:num)/(:num)": ViewLeaderboard/$1/$2/$3

asset:
  type: Asset
  index: index

facebook_profile_source:
  type: FacebookProfileSource
  facebook: facebook

facebook_networks_updater:
  type: FacebookNetworksUpdater
  database: database
  profile_source: facebook_profile_source

network_source:
  type: NetworkSource
  database: database

auth:
  type: FacebookAuth
  facebook: facebook
  database: database
  facebook_permissions:
    - user_birthday
    - user_education_history
    - user_hometown
    - user_events
    - email
    - user_location
    - friends_events
    - friends_education_history
    - offline_access

profile_pic_repository:
  type: ImageRepository
  file_repository: profile_pic_storage

ticket_repository:
  type: ImageRepository
  file_repository: ticket_storage

profile_picture_factory:
  type: ProfilePictureFactory
  database: database
  image_repository: profile_pic_repository

timezone:
  type: DateTimeZone
  timezone: America/New_York

clock:
  type: Clock
  timezone: timezone

session_handler:
  type: DatabaseSessionHandler
  database: database
  clock: clock

package_installer:
  type: PackageInstaller
  database: database
  class_loader: class_loader

test_package_installer:
  type: PackageInstaller
  database: test_database
  class_loader: class_loader

checkin_engine:
  type: CheckinEngine
  database: database
  clock: clock
  event_dispatcher: event_dispatcher

invite_engine:
  type: InviteEngine
  database: database
  clock: clock
  event_dispatcher: event_dispatcher

entourage_engine:
  type: EntourageEngine
  database: database

test_invite_engine:
  type: InviteEngine
  database: test_database
  clock: clock

job_queue:
  type: JobQueue
  database: database
  pusher: pusher

facebook_friend_source:
  type: FacebookFriendSource
  facebook: facebook

facebook_friends_updater:
  type: FacebookFriendsUpdater
  database: database
  friend_source: facebook_friend_source

facebook_profile_updater:
  type: FacebookProfileUpdater
  database: database
  profile_source: facebook_profile_source

mutual_friends_calculator:
  type: MutualFriendsCalculator
  database: database

emailer:
  type: Emailer
  driver: swift
  server: smtp.gmail.com
  port: 465
  encryption: ssl
  username: notifications@whowentout.com
  password: WWO12345
  from: WhoWentOut

invite_leaderboard:
  type: InviteLeaderboard
  database: database
