# TODO: deny access to these directories using .htaccess
app:
  type: WhoWentOutApp
  class_loader: class_loader
  database: database

timezone:
  type: DateTimeZone
  timezone: UTC

clock:
  type: Clock
  timezone: timezone

database:
  type: Database
  host: localhost
  database: wwo
  username: root
  password: root

session_handler:
  type: DatabaseSessionHandler
  database: database
  clock: clock

test_database:
  type: Database
  host: localhost
  database: fire_test
  username: root
  password: root

router:
  type: Router
  app: app

package_installer:
  type: PackageInstaller
  database: database
  class_loader: class_loader
  