database:
  type: Database
  host: db01-share
  database: whowasout_com
  username: Custom App-24732
  password: MySQL4668

facebook:
  type: Facebook
  config:
    appId: 183435348401103
    secret: 2a9ecc98d06840a80c21646cc185eca4

profile_pic_storage:
  type: FileRepository
  driver: s3
  bucket: whowasout_pics
  amazon_public_key: 0N83TDC3E416BETER2R2
  amazon_secret_key: sKpMFrppw9X2KtuvUgJRyZo+O7yvYPluC4ttAwWK

ticket_storage:
  type: FileRepository
  driver: s3
  bucket: whowasout_tickets
  amazon_public_key: 0N83TDC3E416BETER2R2
  amazon_secret_key: sKpMFrppw9X2KtuvUgJRyZo+O7yvYPluC4ttAwWK

pusher:
  type: Pusher
  auth_key: cc920ca581a4b74b17dd
  secret: b9c27ae2c8d15615336c
  app_id: 10140
  debug: true
  timeout: 10

allowed_networks:
  type: Config
  networks:
    - 16777274 #maryland
    - 16777219 #stanford

network_blocker:
  type: NetworkBlocker
  database: database
  allowed_networks:
    - 16777274 #maryland
    - 16777219 #stanford

    