routes:
  "test": TestAction
  "/": ViewHomepage
  "day": ViewDay
  "networks_required": ViewNetworksRequiredDialog
  "day/:date": ViewDay/:date
  "login": Login
  "logout": Logout
  "login/complete": LoginComplete
  "login/as/:num": LoginAs/:num
  "profile/:user": ViewProfile/:user
  "profile/picture/edit": ViewEditProfilePictureDialog
  "profile/picture/facebook": SetProfilePictureToFacebook
  "profile/picture/upload": UploadProfilePicture
  "profile/picture/crop": CropProfilePicture
  "events/:event/invite": ViewInviteDialog/:event
  "events/:event/invite/submit": SendInvites
  "events/:event/deal": ViewDealDialog/:event
  "deal/confirm": ConfirmDeal
  "checkin": Checkin
  "checkin/explanation/:event": ViewCheckinExplanation/:event
  "checkin/explanation/confirm": ConfirmCheckinExplanation
  "admin": AdminView
  "terms": ShowPage/terms
  "mission": ShowPage/mission_statement
  "admin/deals/:date": AdminViewDeals/:date
  "admin/deals": AdminViewDeals
  "admin/places": AdminViewPlaces
  "admin/places/create": AdminCreatePlace
  "admin/places/:place/destroy": AdminDestroyPlace/:place
  "admin/events": AdminViewEvents
  "admin/events/create": AdminCreateEvent
  "admin/events/:event/edit": AdminEditEvent/:event
  "admin/events/update": AdminUpdateEvent
  "admin/events/:event/destroy": AdminDestroyEvent/:event
  "admin/packages": ViewPackages
  "admin/packages/:word/install": InstallPackage/:word
  "admin/packages/:word/update": UpdatePackage/:word
  "admin/emails": AdminViewUnsentEmails
  "admin/emails/update": AdminUpdateEmail
  "admin/emails/run_job": AdminRunEmailJob
  "admin/users/destroy/:user": AdminDestroyUser/:user
  "jobs/run/:alnum": RunJob/:alnum
  "jobs/client": ViewJobsClient
  "entourage": ViewEntourage
  "entourage/accept": AcceptEntourageRequest
  "entourage/invite": ViewEntourageRequestDialog
  "entourage/invite/submit": SendEntourageRequests
  "leaderboard/:date": ViewLeaderboard/:date
